# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: rabdis
    tap:
      owner: JulienBreux
      name: run-cli-homebrew
    commit_author:
      name: Julien Breux
      email: julien.breux@gmail.com
    folder: Formula
    homepage: https://github.com/julienbreux/run-cli/
    description: Run CLI is an interactive CLI to manage your Google Cloud Run resources with panache!
    test: system "run version"

nfpm:
  - maintainer: Julien Breux <julien.breux@gmail.com>
    description: Run CLI.
    homepage: https://gitlab.com/JulienBreux/run-cli
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
